server:
  port: 8081
  servlet:
    context-path: /redis
spring:
  application:
    name: SSO
  cache:
    type: redis
  redis:
    database: 0
    host: 192.168.6.134
    port: 7000
    # 有密码填密码，没有密码不填
    password:
    # 连接超时时间（ms)
    timeout: 1000
    # 高版本springboot中使用jedis或者lettuce
    jedis:
      pool:
        # 连接池最大连接数（负值表示无限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负值无限制)
        max-wait: 5000
        # 最大空闲链接数
        max-idle: 8
        # 最小空闲链接数
        min-idle: 0